# Generated by Django 3.2.20 on 2023-07-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_cliente_remove_exemplar_id_alter_exemplar_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
    ]
