# Generated by Django 4.1 on 2023-07-31 23:21

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_cliente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=biblioteca.models.gerar_nome_arquivo),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano_public',
            field=models.CharField(max_length=10),
        ),
    ]
